apiVersion: batch/v1
kind: Job
metadata:
  name: coherence
  namespace: oniondownloader
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 180
  template:
    spec:
      containers:
      - name: coherence
        image: 10.10.10.106:5000/breacher/coherence:1.0
        imagePullPolicy: Always
      restartPolicy: Never