apiVersion: v1
kind: Service
metadata:
  name: torproxy
  namespace: torproxy
spec:
  ports:
  - port: 9050
    name: socks5
    protocol: TCP
    targetPort: 9050
  - port: 8118
    name: http
    protocol: TCP
    targetPort: 8118
  selector:
    app: torproxy