apiVersion: batch/v1
kind: Job
metadata:
  name: update
  namespace: oniondownloader
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 180
  template:
    spec:
      containers:
      - name: update
        image: 10.10.10.106:5000/breacher/update:1.0
        imagePullPolicy: Always
      restartPolicy: Never