apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alerts-pv
  labels:
    type: local
spec:
  storageClassName: 'prometheus-alerts-pv'
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/usr/share/prometheus-alerts"
