apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data-pv
  labels:
    type: local
spec:
  storageClassName: 'prometheus-data-pv'
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/usr/share/prometheus-data"
