apiVersion: v1
kind: Service
metadata:
  name: crawlab
  namespace: crawlab
spec:
  ports:
  - name: http
    port: 8080
    nodePort: 30106
  - name: grpc
    port: 9666
    targetPort: 9666
  selector:
    app: crawlab-master
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawlab-master
  namespace: crawlab
spec:
  selector:
    matchLabels:
      app: crawlab-master
  template:
    metadata:
      labels:
        app: crawlab-master
    spec:
      containers:
      - image: crawlabteam/crawlab:latest
        imagePullPolicy: Always
        name: crawlab
        env:
        - name: CRAWLAB_NODE_MASTER
          value: "Y"
        - name: CRAWLAB_MONGO_HOST
          value: "mongo"
        - name: CRAWLAB_REDIS_ADDRESS
          value: "redis"
        - name: CRAWLAB_SETTING_ALLOWREGISTER
          value: "Y"
        - name: CRAWLAB_SERVER_LANG_NODE
          value: "N"
        - name: CRAWLAB_SERVER_LANG_JAVA
          value: "N"
        - name: CRAWLAB_SERVER_LANG_DOTNET
          value: "N"
        - name: CRAWLAB_SERVER_REGISTER_TYPE
          value: "hostname"
        ports:
        - containerPort: 8080
          name: crawlab
        - containerPort: 9666
          name: grpc