apiVersion: v1
kind: Service
metadata:
  name: crawlab
  namespace: crawlab
spec:
  ports:
  - name: http
    port: 8080
    nodePort: 30106
  - name: grpc
    port: 9666
    targetPort: 9666
  selector:
    app: crawlab-master
  type: LoadBalancer