apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: crawlab
spec:
  ports:
  - port: 27017
  selector:
    app: mongo
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: mongo
  namespace: crawlab
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: mongo:4
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        command:
          - mongod
          - "--replSet"
          - rs0
          - "--bind_ip_all"   
          # Execute in mongodb pod:
          # rs.initiate({_id:"rs0", version: 1, members: [ {_id: 0, host: "mongo.crawlab.svc.cluster.local:27017"} ]})
          # use crawlab_test 
          # db.results_onions_farmer.createIndex({"onion":1},{unique:true})
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi