apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: sparkjob
  namespace: spark
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: http://PRIVATE_DOCKER_REGISTRY/breacher/sparkjob:1.0
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/main.py"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark-user
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 3.0.0
  deps:
    jars:
      - https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.2.0/hadoop-aws-3.2.0.jar
      - https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.375/aws-java-sdk-bundle-1.11.375.jar